export const FETCH_ALL_VOTERS_REQUEST = 'FETCH_ALL_VOTERS_REQUEST';
export const FETCH_ALL_VOTERS_SUCCESS = 'FETCH_ALL_VOTERS_SUCCESS';
export const FETCH_ALL_VOTERS_FAILURE = 'FETCH_ALL_VOTERS_FAILURE';

export const SEARCH_BY_NAME_REQUEST = 'SEARCH_BY_NAME_REQUEST';
export const SEARCH_BY_NAME_SUCCESS = 'SEARCH_BY_NAME_SUCCESS';
export const SEARCH_BY_NAME_FAILURE = 'SEARCH_BY_NAME_FAILURE';

export const FILTER_BY_CASTED_STATUS_REQUEST = 'FILTER_BY_CASTED_STATUS_REQUEST';
export const FILTER_BY_CASTED_STATUS_SUCCESS = 'FILTER_BY_CASTED_STATUS_SUCCESS';
export const FILTER_BY_CASTED_STATUS_FAILURE = 'FILTER_BY_CASTED_STATUS_FAILURE';

export const UPDATE_VOTER_REQUEST = 'UPDATE_VOTER_REQUEST';
export const UPDATE_VOTER_SUCCESS = 'UPDATE_VOTER_SUCCESS';
export const UPDATE_VOTER_FAILURE = 'UPDATE_VOTER_FAILURE';

export const FETCH_CONSISTENCY_NAMES_REQUEST = 'FETCH_CONSISTENCY_NAMES_REQUEST';
export const FETCH_CONSISTENCY_NAMES_SUCCESS = 'FETCH_CONSISTENCY_NAMES_SUCCESS';
export const FETCH_CONSISTENCY_NAMES_FAILURE = 'FETCH_CONSISTENCY_NAMES_FAILURE';


export const FETCH_BOOTH_NAMES_REQUEST = 'FETCH_BOOTH_NAMES_REQUEST';
export const FETCH_BOOTH_NAMES_SUCCESS = 'FETCH_BOOTH_NAMES_SUCCESS';
export const FETCH_BOOTH_NAMES_FAILURE = 'FETCH_BOOTH_NAMES_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';